# Generated by Django 4.0.5 on 2022-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_add_pagerelatedpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="site_name",
            field=models.CharField(
                blank=True,
                default="wagtail testing",
                help_text="Site name, used by Open Graph.",
                max_length=255,
            ),
        ),
    ]
